### ISSUE TITLE
Saving template to JSON creates invalid file

### ISSUE THREAD

**Issue by matthewcorven** [neodynamic/ThermalLabel-SDK#1]
1. Create template initially with WinForms demo, in order to set Sheet Labels Margin (ex: 18 points top, 18 points left). Save template as JSON.
2. Open template with Razor demo.  Save again as JSON.
3. Reload Razor demo web app.  Attempt to open JSON template created in preceding step.  Error occurs.
4. Open JSON template in text editor.  Notice that values for property SheetLabelsMargin are not surrounded by quotes, and are therefore invalid.

### Example Template content:

{"ThermalLabel":{"Version":10.0,"Width":576,"Height":756,"GapLength":0,"MarkLength":0,"OffsetLength":0,"UnitType":"Point","LabelsPerRow":1,"LabelsHorizontalGapLength":0,"IsContinuous":false,"PrintSpeed":"","PrintMirror":false,"CutAfterPrinting":false,"SheetLabelsWidth":612,"SheetLabelsHeight":792,"SheetLabelsCount":1,"SheetLabelsMargin":**18,18,0,0**,"Items":[{"Type":"TextItem","DataField":"PharmacyLegalName","Width":135,"Height":9,"Text":"[PharmacyLegalName]","Font":"Arial,7,True,False,False,False,Point,,,False,90,,CP850","CultureName":"en-US"},{"Type":"TextItem","X":54,"Y":9,"DataField":"PharmacyLegalName","Width":135,"Height":9,"Text":"[PharmacyLegalName]","Font":"Arial,7,True,False,False,False,Point,,,False,90,,CP850","CultureName":"en-US"},{"Type":"BarcodeItem","X":200.25,"Y":22.50000000000001,"DataField":"RxNumber","Width":153,"Height":22.5,"Symbology":"Code39","Code":"1234567890","AztecCodeModuleSize":3.0023999999999997,"BarHeight":21,"BarWidth":0.7487999999999999,"BearerBarThickness":3.5999999999999996,"DataMatrixModuleSize":3.0023999999999997,"DisplayCode":false,"DisplayStartStopChar":false,"EanUpcGuardBarHeight":39.599999999999994,"EanUpcSupplementSeparation":10.8,"EanUpcSupplementTopMargin":10.8,"Font":"NativePrinterFontA,10,Point,,,False,90,,CP850","PharmacodeBarsSpacing":3.0023999999999997,"PharmacodeThickBarWidth":4.5,"PharmacodeThinBarWidth":1.4975999999999998,"PlanetHeightShortBar":7.199999999999999,"PlanetHeightTallBar":14.4,"Postal4StateBarsSpacing":2.2536,"Postal4StateTrackerBarHeight":5.76,"Postal4StateTrackerBarWidth":1.4975999999999998,"PostnetHeightShortBar":7.199999999999999,"PostnetHeightTallBar":14.4,"QRCodeModuleSize":3.0023999999999997,"QuietZone":"7.199999999999999,0,7.199999999999999,1.44","RotationAngle":90,"Sizing":"FitProportional","TextFont":"NativePrinterFontA,10,Point,,,False,90,,CP850","HanXinCodeModuleSize":3.0023999999999997,"MaxiCodeDrawPixelBasedSymbol":true,"DotCodeModuleSize":3.0023999999999997},{"Type":"TextItem","Y":18,"Width":20,"Height":9,"Text":"RX","Font":"Arial,7,Point,,,False,90,,CP850","CultureName":"en-US"},{"Type":"TextItem","X":22.5,"Y":18,"DataField":"RxNumber","Width":49.99999999999999,"Height":9,"Text":"RxNumber","Font":"Arial,7,True,False,False,False,Point,,,False,90,,CP850","CultureName":"en-US"}]}}

**Comment by neodynamic** [comment]
Update to the latest build (SDK, Editors, JS files) [from NuGet](https://www.nuget.org/packages?q=ThermalLabel) or [from our website](https://www.neodynamic.com/products/printing/thermal-label/sdk-vb-net-csharp/download/) because a new JSON format was released.
